### ISSUE TITLE
🦺[Tech Debt] Add  Linter `Swift Format` 

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#144]
## Goal 
**Describe the work to be done**
 
`A small step for man a giant leap for mankind` - Armstrong

This code has needed a linter for years but the task was **huge**.  So many classes fail the linter (the one @kcw-grunt is familiar with).  Maybe fresh eyes can fix the issue.

## References
https://github.com/nicklockwood/SwiftFormat

```
let package = Package(
    name: "BuildTools",
    platforms: [.macOS(.v10_11)],
    dependencies: [
        .package(url: "https://github.com/nicklockwood/SwiftFormat", from: "0.49.0"),
    ],
    targets: [.target(name: "BuildTools", path: "")]
)
```

## Definition of Done
- [ ] Removes headers
- [ ] Auto to Xcode format standards (4 tab, \ n only between lines
- [ ] Other suggestions

**Comment by Iferencak** [comment]
Discussion:
How do we feel about using `SwiftLint` instead of `SwiftFormat`?

Why I'm having second second thoughts about `SwiftFormat`?
I tested out `SwiftFormat`, I had it setup as a run script. As soon as I built the app, all of the app code was automatically formatted. That is cool, but it also auto-formatted the pods, and removed some `self.`'s from the code where they were needed, causing the app to fail the build. Now, I'm sure that it can be configured so it does not touch the pods, but I'm just not sure how comfortable I feel about `SwiftFormat` making changes and rewriting files on it's own. 

The second thing is, as much as it's cool to have your code automatically formatted, `SwiftLint` offers more rules about function, class and file sizes, and it makes the developer think more about the code he is writing and how to optimize it. My thoughts are that the developers working on the app (and with that the app itself) would benefit much more from having to format their code on their own, with the warnings that `SwiftLint` provides. 

I'm open to implementing both solutions, just wanted to discuss it with you @kcw-grunt. What do you think?

**Comment by kcw-grunt** [comment]
Hey @Iferencak this is a great discussion.

To be honest I have been using SwiftFormat to manage keep the code clean and not in Litewallet.

So, if you look at the default config [`.swiftformat`](https://github.com/nicklockwood/SwiftFormat/blob/master/.swiftformat)  you can actually turn much of the formatting off and in fact use it as a linter. Please forgive the title of the issue.

For that reason, I was thinking nerfing SwiftFormat to a Linter first gives us more flexibilty

In the notes in SwiftFormat they mention the same thing you mention which is you dont want things auto-formatted.  But, I'm a terrbile formatter as my workflow, so I use it mainly for that.

I hate a linter that forces me to go add spaces / tabs while I'm in dev mode.

Will you play with SwiftFormat and its [Linter](https://github.com/nicklockwood/SwiftFormat#linting) capabilities and we can discuss further next week?

**Comment by Iferencak** [comment]
Sure thing! I'll do a deeper dive and implement the things I find most usefull for start. Let's expand it from there.

**Comment by kcw-grunt** [comment]
Thanks @Iferencak ...I felt this issue was tricky but in the grand scheme of wrangling the code I felt it was an obvious thing we should address
