### ISSUE TITLE
🦟[Bug Report] Crashlytics: TransactionsViewController.swift line 48

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#148]
**Describe the bug**

Per the info given in Crashlytics there is a recurring crash in TransactionsViewController.swift

## Notes
A quick look suggests the output `PromptType` is an optional and it may be nil in many cases.

## Log

`
Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of sections. The number of sections contained in the table view after the update (2) must be equal to the number of sections contained in the table view before the update (2), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted). Table view: <UITableView: 0x108105c00; frame = (0 0; 428 736); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x282502af0>; layer = <CALayer: 0x282b7e4c0>; contentOffset: {0, 0}; contentSize: {428, 5688}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <loafwallet.TransactionsViewController: 0x1036272b0>>
`

## Crashlytics Link
https://console.firebase.google.com/project/litewallet-beta/crashlytics/app/ios:com.litecoin.loafwallet/issues/a0dc29c574d796b2ab76a1975cd69584?time=last-seven-days&sessionEventKey=6cc77f58637845558553d26f913d863a_1741566258082075577
**Screenshots**

**Observed Environment**
 - OS version [e.g. _iOS 13.0_]:
 - Litewallet Version [e.g. _v3.4.0_]:
 - Device model:[e.g. _iPhone 11_]:

**Additional context or information**

**Comment by Iferencak** [comment]
`PromptType` being nil was handled in code. 

The issue was that there was attempt to insert a new section, but when this happened, the data source stayed the same and the app crashed as it expected to have one more section.
`tableView.insertSections(IndexSet(integer: 0), with: .automatic)`

I tried to understand the code and it looks to me that the original author just wanted to reload a section here and not insert a new one. Doing that fixes the issue and everything works as it should.
`tableView.reloadSections(IndexSet(integer: 0), with: .automatic)`
