### ISSUE TITLE
Improve Resyncing 

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#34]
Syncing to the latest blockchain can take time and the delay is unpleasant .  We need to improve the experience.

**Comment by losh11** [comment]
This isn't possible due to the way BIP32 works. We don't know the birthday block of the user's wallet, so quick-syncing without the use of a centralised service will not be possible. The only way this could be done is to add the aezeed cipher scheme which encodes the birthday block as part of the 24-word seed.

**Comment by kcw-grunt** [comment]
Closing. `cfilter` make improve this
