### ISSUE TITLE
Allow testnet mode 

### ISSUE THREAD

**Issue by alekplay** [litecoin-foundation/loafwallet-ios#71]
I'd love for LoafWallet to have an option for testnet mode when setting up the wallet, similar to Copay. There are no LTC testnet wallets on iOS, which makes developing in the ecosystem difficult when you have to rely on Electrum and other desktop clients.

**Comment by losh11** [comment]
Internally LoafWallet does support testnet mode for developers. If you open
the project in Xcode, there are testnet build targets available. Developers
are suggested to use this.

I feel that adding UI internally increases code complexity unnecessarily &
makes UI more confusing to regular users.

**Comment by alekplay** [comment]
> Internally LoafWallet does support testnet mode for developers. If you open the project in Xcode, there are testnet build targets available. Developers are suggested to use this. I feel that adding UI internally increases code complexity unnecessarily & makes UI more confusing to regular users.

More than just developers use testnet mode - early adopters of crypto software as well are among them, but we are forced to rely on BTC and BCH which are provided in a very clean way through [Copay](https://itunes.apple.com/us/app/copay-bitcoin-wallet/id951330296?mt=8).

As an example it could be an option in the settings menu when resetting your wallet, that way casual users are automatically directed to mainnet as they are now, but power users can go in and create a testnet wallet if they wish.

**Comment by kcw-grunt** [comment]
Hi @alekplay I just picked up technical lead for all Loafwallet and BRCore **does** need to be updated to allow tLTC for the Loafwallet.  I agree it is needed and it is in the horizon.  

This was apparent when initial talks with our partners who are using tLTC for the dev and staging environments.  Look for movement in <2 months.

**Comment by kcw-grunt** [comment]
@alekplay  the update is imminent but there are other issues being focused on first.  If you want to try, pull the loafwallet-ios Xcode project, run cocoapods and  using the Testnet scheme and commenting out lines 123 - 125 of BRAPIClient.swift will give you a running project.  The problem is produces _tBTC_ **not**  tLTC.

The fix is to fork loafwallet-core (https://github.com/litecoin-foundation/loafwallet-core) to refactor tBTC components....

It's on my plate but you are welcome to take a crack at it first.
